### ISSUE TITLE
Line 198, list index out of range

### ISSUE THREAD

**Issue by YamiOdymel** [aaaddress1/PykemonGo#1]
Line 788, Starting new HTTPS connection (1): android.clients.google.com
Line 788, Starting new HTTPS connection (1): android.clients.google.com
Line 64, Coordinates: 35.6826121 139.685873 0.0
Line 788, Starting new HTTPS connection (1): pgorelease.nianticlabs.com
Line 31, Printing Profile:
Line 198, list index out of range

Traceback (most recent call last):
  File "main.py", line 390, in <module>
    getProfile(session)
  File "main.py", line 32, in getProfile
    profile = session.getProfile()
  File "/Users/YamiOdymel/PykemonGo/pogo/session.py", line 245, in getProfile
    res = self.wrapAndRequest(payload)
  File "/Users/YamiOdymel/PykemonGo/pogo/session.py", line 149, in wrapAndRequest
    self.parseDefault(res)
  File "/Users/YamiOdymel/PykemonGo/pogo/session.py", line 199, in parseDefault
    raise GeneralPogoException("Error parsing response. Malformed response")
custom_exceptions.GeneralPogoException: Error parsing response. Malformed response

**Comment by YamiOdymel** [comment]
換個帳號重新註冊解決問題。
